@extends('layouts.app')

@section('title', 'Operator Dashboard')

@section('extraCss')
    <link rel="stylesheet" href="https://cdn.datatables.net/1.13.6/css/jquery.dataTables.min.css">
@endsection
@section('content')

    <!-- Header -->
    <header class="bg-blue-900 text-white py-4 shadow">
        <div class="max-w-7xl mx-auto px-4">
            <div class="flex justify-between items-center">
                <h1 class="text-2xl font-bold">Teacher's Appointment Letter Generation System, BTR</h1>
            </div>

            <!-- Tabs -->
            <div class="mt-4 flex space-x-4 border-b border-blue-700">
                <a href="{{ route('operator.index') }}" id="tabCandidate"
                    class="py-2 px-4 text-sm font-medium border-b-2 border-transparent hover:border-white focus:outline-none">
                    Candidates
                </a>
                <a href="{{ route('operator.CurrentVacency') }}" id="tabRemaining"
                    class="py-2 px-4 text-sm font-medium border-b-2 border-transparent hover:border-white focus:outline-none">
                    Vacency
                </a href="">
            </div>
        </div>
    </header>
    <!-- Go Back Button -->
    <div class="max-w-7xl w-full mx-auto px-4 mt-4">
        <a href="{{ route('operator.index') }}" class="inline-flex items-center text-blue-700 hover:text-blue-900">
            <svg class="w-6 h-6" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24" xmlns="operator">
                <path stroke-linecap="round" stroke-linejoin="round" d="M15 19l-7-7 7-7" />
            </svg> 
            <span>Back to Candidates</span>
        </a>
    </div>

    {{-- *** Show Error Message Pop up *** --}}


    <!-- Main Content -->
    <main class="max-w-7xl w-full mx-auto px-4 py-8 space-y-6">
            <div class="mb-6">
                <h2 class="text-xl font-semibold text-blue-800">Candidate Details</h2>
            </div>

        <!-- Candidate Info -->
        <section class="bg-white shadow-md p-10 border border-gray-200">
            <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4 text-sm text-gray-700">
                <div class="uppercase"><strong class="text-gray-700">Roll Number:</strong> {{ $resData['candDetails']->rollNumber ?? 'Not Mention' }}</div>
                <div class="uppercase"><strong class="text-gray-700">Name:</strong> {{ $resData['candDetails']->name ?? 'Not Mention' }}</div>
                <div class="uppercase"><strong class="text-gray-700">Post:</strong> {{ $resData['candDetails']->allpost->name ?? 'Not Mention' }}</div>
                <div class="uppercase"><strong class="text-gray-700">Father's Name:</strong> {{ $resData['candDetails']->fatherName ?? 'Not Mention' }}</div>
                <div class="uppercase"><strong class="text-gray-700">Address:</strong> {{ $resData['candDetails']->address ?? 'Not Mention' }}</div>
                <div class="uppercase"><strong class="text-gray-700">District:</strong> {{ $resData['candDetails']->district ?? 'Not Mention' }}</div>
                @if ($resData['candDetails']->allpost->id == 2)
                    <div class="uppercase"><strong class="text-gray-700">PIN Code:</strong> {{ $resData['candDetails']->pinCode ?? 'Not Mention' }}</div>
                @endif

                {{-- Conditional Fields --}}
                @if ($resData['candDetails']->allpost->id == 1)
                    <div class="uppercase"><strong class="text-gray-700">Medium:</strong> {{ $resData['candDetails']->medium ?? 'Not Mention' }}</div>
                    <div class="uppercase"><strong class="text-gray-700">Stream:</strong> {{ $resData['candDetails']->category ?? 'Not Mention' }}</div>
                @elseif ($resData['candDetails']->allpost->id == 2)
                    <div class="uppercase"><strong class="text-gray-700">Subject:</strong> {{ $resData['candDetails']->subject ?? 'Not Mention' }}</div>
                @endif

                {{-- Optional Fields (commented out) --}}
                {{-- 
                <div class="uppercase"><strong class="text-gray-700">Allocated School Code:</strong> {{ $resData['candDetails']->allocatedSchoolCode ?? 'Not Mention' }}</div>
                <div class="uppercase"><strong class="text-gray-700">Generated By:</strong> {{ $resData['candDetails']->generatedBy ?? 'Not Mention' }}</div>
                <div class="uppercase"><strong class="text-gray-700">Generated On:</strong> {{ $resData['candDetails']->generatedOn ?? 'Not Mention' }}</div>
                <div class="uppercase"><strong class="text-gray-700">Allocated Status:</strong> {{ $resData['candDetails']->isAllocated ?? 'Not Mention' }}</div>
                --}}
            </div>



            <div class="flex items-center justify-center mt-6">
                <a href="{{ route('operator.downloadAppoint', ['candRoll' => $resData['candRoll'] ?? null]) }}" download
                    class="inline-flex items-center px-4 py-2 bg-blue-600 text-white font-semibold shadow hover:bg-blue-700 transition duration-200 {{$resData['candDetails']->isAllocated == 1 ?'' : 'hidden'}}" id="download-appoint">
                    ⬇️ Download PDF
                </a>
            </div>

        </section>

        @if (($resData['statusCode'] ?? 400) == 400)
            <div class="max-w-md mx-auto">
                <div
                    class="flex items-start space-x-3 bg-red-50 border border-red-400 text-red-800 px-4 py-3 rounded-md shadow-sm">
                    <!-- Icon (optional) -->
                    <svg class="w-5 h-5 mt-1 text-red-600" fill="none" stroke="currentColor" stroke-width="2"
                        viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                        <path stroke-linecap="round" stroke-linejoin="round"
                            d="M12 9v2m0 4h.01M4.93 4.93l14.14 14.14M12 2a10 10 0 100 20 10 10 0 000-20z" />
                    </svg>

                    <!-- Error Message Text -->
                    <div class="text-sm font-medium">
                        {{ $resData['message'] ?? 'Server error please try later ' }}
                    </div>
                </div>
            </div>
        @else
            <div class="max-w-xl w-full mx-auto mt-10">
                <div class="bg-white border shadow-md p-10">
                    <h2 class="text-lg font-semibold text-blue-800 mb-6">Search by School Code</h2>

                    <form class="space-y-4" id="allocate-form">
                        <div>
                            <label for="schoolCode" class="block text-sm font-medium text-gray-700">Preferred School Code</label>
                            <input type="text" name="schoolCode" id="schoolCode" required placeholder="Enter School Code"
                                class="mt-1 block w-full rounded-md border border-gray-300 shadow-sm px-3 py-2 text-sm focus:ring-blue-500 focus:border-blue-500">
                            <input type="hidden" name="candRoll" value="{{ $resData['candRoll'] ?? null }}">
                        </div>

                        <!-- New Select Box -->
                        <div>
                            <label for="schoolType" class="block text-sm font-medium text-gray-700">Select School
                                Type</label>
                            <select name="postID" id="schoolType"
                                class="mt-1 block w-full rounded-md border border-gray-300 shadow-sm px-3 py-2 text-sm focus:ring-blue-500 focus:border-blue-500">
                                <option value="" selected disabled>-- Select Post Type --</option>
                                @foreach ($resData['posts'] ?? [] as $post)
                                    <option value="{{ $post->id ?? 0 }}">{{ $post->name ?? null }}</option>
                                @endforeach
                            </select>
                        </div>

                        <div>
                            <button type="submit"
                                class="w-full bg-blue-700 hover:bg-blue-800 text-white font-medium py-2 px-4 rounded-md transition mt-6"
                                id="allocate-btn">
                                Search
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        @endif

    </main>

@endsection

@section('extraJs')

    <script src="https://cdn.datatables.net/1.13.6/js/jquery.dataTables.min.js"></script>
    <script type="module" src="{{ asset('js/Operator/operator.js') }}"></script>
@endsection
